#! /bin/bash

set -eu

TABLE_NAME="$(jq < cfn-output.json -r '.DynamoTable')"

SCRIPTPATH=$(dirname "$0")

sed -i "s/DDB_TABLE_NAME/$TABLE_NAME/g" "$SCRIPTPATH/ddb/populate-dynamodb.json"

aws dynamodb batch-write-item --request-items file://$SCRIPTPATH/ddb/populate-dynamodb.json
