#! /bin/bash

set -eu

echo "Installing dependencies..."
sudo yum install -y jq
echo "Fetching CloudFormation outputs..."
bootstrap/fetch-outputs
echo "Populating DynamoDB table..."
bootstrap/load-ddb
echo "Success!"
