#! /bin/bash

set -eu

echo "Installing dependencies..."
sudo yum install -y jq
echo "Fetching CloudFormation outputs..."
bootstrap/fetch-outputs
echo "Populating DynamoDB table..."
bootstrap/ddb/load-ddb
echo "Success!"
echo "Building Docker containers"
bootstrap/docker/build-containers
bootstrap/docker/update-service-json
bootstrap/docker/create-fargate-service
echo "Assigning Instance Profile"
bootstrap/associate-profile
