#!/bin/bash

SERVICE_ECR_REPO=$(jq < cfn-output.json -r '.MythicalServiceEcrRepo')
XRAY_ECR_REPO=$(jq < cfn-output.json -r '.XrayEcrRepo')

$(aws ecr get-login --no-include-email)

docker build -t service:latest app
docker tag service:latest $SERVICE_ECR_REPO:latest
docker push $SERVICE_ECR_REPO:latest

docker build -t x-ray-daemon app/xray
docker tag x-ray-daemon:latest $XRAY_ECR_REPO:latest
docker push $XRAY_ECR_REPO:latest
