#!/bin/bash

SERVICE_ECR_REPO=$(jq < cfn-output.json -r '.MythicalServiceEcrRepo')
# MONO_ECR_REPO=$(jq < cfn-output.json -r '.MonoEcrRepo')

$(aws ecr get-login --no-include-email)

docker build -t service:latest app
docker tag service:latest $SERVICE_ECR_REPO:latest
docker push $SERVICE_ECR_REPO:latest
